frr version 9
frr defaults traditional
hostname tor-c12
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.2.12/32

router bgp 65002
 bgp router-id 10.255.2.12
 no bgp default ipv4-unicast

 neighbor AGG-C2 peer-group
 neighbor AGG-C2 remote-as 65002
 neighbor AGG-C2 update-source lo
 neighbor 10.255.0.32 peer-group AGG-C2

 address-family l2vpn evpn
  neighbor AGG-C2 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.2.12:10102
  route-target import 65102:10102
  route-target export 65102:10102