frr version 9
frr defaults traditional
hostname tor-c2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.5.2/32

interface eth1
 ip address 10.255.10.3/31

router bgp 65002
 bgp router-id 10.255.5.2
 no bgp default ipv4-unicast

 neighbor AGG-C1 peer-group
 neighbor AGG-C1 remote-as 65002
 neighbor AGG-C1 update-source lo
 neighbor 10.255.0.31 peer-group AGG-C1

 address-family l2vpn evpn
  neighbor AGG-C1 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.5.2:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.5.2
 network 10.255.0.0/16 area 0