frr version 9
frr defaults traditional
hostname tor-c3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.2.3/32

router bgp 65002
 bgp router-id 10.255.2.3
 no bgp default ipv4-unicast

 neighbor AGG-C1 peer-group
 neighbor AGG-C1 remote-as 65002
 neighbor AGG-C1 update-source lo
 neighbor 10.255.0.31 peer-group AGG-C1

 address-family l2vpn evpn
  neighbor AGG-C1 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.2.3:10101
  route-target import 65101:10101
  route-target export 65101:10101