frr version 9
frr defaults traditional
hostname agg-t1
log syslog informational
service integrated-vtysh-config

!
! Loopback
!
interface lo
 ip address 10.255.0.51/32
 ip ospf area 0
 ip ospf passive

!

!
! Underlay links
! core-t:eth1 <-> agg-t1:eth1
!
interface eth1
 ip address 10.255.1.1/31
!

! agg-t1:eth2 <-> tor-t1:eth1
interface eth2
 ip address 10.255.10.0/31
!

! agg-t1:eth3 <-> tor-t2:eth1
interface eth3
 ip address 10.255.10.2/31
!

! agg-t1:eth4 <-> tor-t3:eth1
interface eth4
 ip address 10.255.10.4/31
!

! agg-t1:eth5 <-> tor-t4:eth1
interface eth5
 ip address 10.255.10.6/31
!

! agg-t1:eth6 <-> tor-t5:eth1
interface eth6
 ip address 10.255.10.8/31
!

! agg-t1:eth7 <-> tor-t6:eth1
interface eth7
 ip address 10.255.10.10/31
!

router bgp 65003
 bgp router-id 10.255.0.51
 no bgp default ipv4-unicast

 !
 ! iBGP to CORE-T (loopback-to-loopback)
 !
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 !
 ! iBGP to ToRs (loopback-to-loopback, RR)
 !
 neighbor TOR-T1 peer-group
 neighbor TOR-T1 remote-as 65003
 neighbor TOR-T1 update-source lo

 neighbor 10.255.3.1 peer-group TOR-T1
 neighbor 10.255.3.2 peer-group TOR-T1
 neighbor 10.255.3.3 peer-group TOR-T1
 neighbor 10.255.3.4 peer-group TOR-T1
 neighbor 10.255.3.5 peer-group TOR-T1
 neighbor 10.255.3.6 peer-group TOR-T1

 address-family l2vpn evpn
  neighbor CORE-T activate
  neighbor TOR-T1 activate
  neighbor TOR-T1 route-reflector-client
  advertise-all-vni
 exit-address-family
!

evpn
 vni 10101 l2
  rd 10.255.0.51:10101
  route-target import 65101:10101
  route-target export 65101:10101
!
router ospf
 router-id 10.255.0.51
 network 10.255.0.51/32 area 0
 network 10.255.1.1/31 area 0
