frr version 9
frr defaults traditional
hostname agg-t2
log syslog informational
service integrated-vtysh-config

!
! Loopback
!
interface lo
 ip address 10.255.0.52/32
!

!
! Underlay links
! core-t:eth2 <-> agg-t2:eth1
!
interface eth1
 ip address 10.255.1.3/31
!

! agg-t2:eth2 <-> tor-t7:eth1
interface eth2
 ip address 10.255.20.0/31
!

! agg-t2:eth3 <-> tor-t8:eth1
interface eth3
 ip address 10.255.20.2/31
!

! agg-t2:eth4 <-> tor-t9:eth1
interface eth4
 ip address 10.255.20.4/31
!

! agg-t2:eth5 <-> tor-t10:eth1
interface eth5
 ip address 10.255.20.6/31
!

! agg-t2:eth6 <-> tor-t11:eth1
interface eth6
 ip address 10.255.20.8/31
!

! agg-t2:eth7 <-> tor-t12:eth1
interface eth7
 ip address 10.255.20.10/31
!

router bgp 65003
 bgp router-id 10.255.0.52
 no bgp default ipv4-unicast

 !
 ! iBGP to CORE-T
 !
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 !
 ! iBGP to ToRs (RR)
 !
 neighbor TOR-T2 peer-group
 neighbor TOR-T2 remote-as 65003
 neighbor TOR-T2 update-source lo

 neighbor 10.255.3.7 peer-group TOR-T2
 neighbor 10.255.3.8 peer-group TOR-T2
 neighbor 10.255.3.9 peer-group TOR-T2
 neighbor 10.255.3.10 peer-group TOR-T2
 neighbor 10.255.3.11 peer-group TOR-T2
 neighbor 10.255.3.12 peer-group TOR-T2

 address-family l2vpn evpn
  neighbor CORE-T activate
  neighbor TOR-T2 activate
  neighbor TOR-T2 route-reflector-client
  advertise-all-vni
 exit-address-family
!

evpn
 vni 10101 l2
  rd 10.255.0.52:10101
  route-target import 65101:10101
  route-target export 65101:10101
!