frr version 9
frr defaults traditional
hostname agg-t2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.52/32

router bgp 65003
 bgp router-id 10.255.0.52
 no bgp default ipv4-unicast

 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 neighbor TOR-T2 peer-group
 neighbor TOR-T2 remote-as 65003
 neighbor TOR-T2 update-source lo

 neighbor 10.255.3.7  peer-group TOR-T2
 neighbor 10.255.3.8  peer-group TOR-T2
 neighbor 10.255.3.9  peer-group TOR-T2
 neighbor 10.255.3.10 peer-group TOR-T2
 neighbor 10.255.3.11 peer-group TOR-T2
 neighbor 10.255.3.12 peer-group TOR-T2

 address-family l2vpn evpn
  neighbor CORE-T activate
  neighbor TOR-T2 activate
  neighbor TOR-T2 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.0.52:10102
  route-target import 65102:10102
  route-target export 65102:10102