frr version 9
frr defaults traditional
hostname agg-t3
log syslog informational
service integrated-vtysh-config

!
! Loopback
!
interface lo
 ip address 10.255.0.53/32
 ip ospf area 0
 ip ospf passive

!

!
! Underlay links
! core-t:eth3 <-> agg-t3:eth1
!
interface eth1
 ip address 10.255.1.5/31
!

! agg-t3:eth2 <-> tor-t13:eth1
interface eth2
 ip address 10.255.30.0/31
!

! agg-t3:eth3 <-> tor-t14:eth1
interface eth3
 ip address 10.255.30.2/31
!

! agg-t3:eth4 <-> tor-t15:eth1
interface eth4
 ip address 10.255.30.4/31
!

! agg-t3:eth5 <-> tor-t16:eth1
interface eth5
 ip address 10.255.30.6/31
!

! agg-t3:eth6 <-> tor-t17:eth1
interface eth6
 ip address 10.255.30.8/31
!

! agg-t3:eth7 <-> tor-t18:eth1
interface eth7
 ip address 10.255.30.10/31
!

router bgp 65003
 bgp router-id 10.255.0.53
 no bgp default ipv4-unicast

 !
 ! iBGP to CORE-T
 !
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 !
 ! iBGP to ToRs (RR)
 !
 neighbor TOR-T3 peer-group
 neighbor TOR-T3 remote-as 65003
 neighbor TOR-T3 update-source lo

 neighbor 10.255.3.13 peer-group TOR-T3
 neighbor 10.255.3.14 peer-group TOR-T3
 neighbor 10.255.3.15 peer-group TOR-T3
 neighbor 10.255.3.16 peer-group TOR-T3
 neighbor 10.255.3.17 peer-group TOR-T3
 neighbor 10.255.3.18 peer-group TOR-T3

 address-family l2vpn evpn
  neighbor CORE-T activate
  neighbor TOR-T3 activate
  neighbor TOR-T3 route-reflector-client
  advertise-all-vni
 exit-address-family
!

evpn
 vni 10101 l2
  rd 10.255.0.53:10101
  route-target import 65101:10101
  route-target export 65101:10101
!
router ospf
 router-id 10.255.0.53
 network 10.255.0.53/32 area 0
 network 10.255.1.5/31 area 0
