frr version 9
frr defaults traditional
hostname agg-t3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.53/32

router bgp 65003
 bgp router-id 10.255.0.53
 no bgp default ipv4-unicast

 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 neighbor TOR-T3 peer-group
 neighbor TOR-T3 remote-as 65003
 neighbor TOR-T3 update-source lo

 neighbor 10.255.3.13 peer-group TOR-T3
 neighbor 10.255.3.14 peer-group TOR-T3
 neighbor 10.255.3.15 peer-group TOR-T3
 neighbor 10.255.3.16 peer-group TOR-T3
 neighbor 10.255.3.17 peer-group TOR-T3
 neighbor 10.255.3.18 peer-group TOR-T3

 address-family l2vpn evpn
  neighbor CORE-T activate
  neighbor TOR-T3 activate
  neighbor TOR-T3 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10103 l2
  rd 10.255.0.53:10103
  route-target import 65103:10103
  route-target export 65103:10103