frr version 9
frr defaults traditional
hostname core-t
log syslog informational
service integrated-vtysh-config

!
! Loopback
!
interface lo
 ip address 10.255.0.41/32
!

!
! Underlay links
! core-t:eth1 <-> agg-t1:eth1
!
interface eth1
 ip address 10.255.1.0/31
!

! core-t:eth2 <-> agg-t2:eth1
interface eth2
 ip address 10.255.1.2/31
!

! core-t:eth3 <-> agg-t3:eth1
interface eth3
 ip address 10.255.1.4/31
!

router bgp 65003
 bgp router-id 10.255.0.41
 no bgp default ipv4-unicast

 !
 ! iBGP to AGGs (loopback-to-loopback)
 !
 neighbor AGG-T peer-group
 neighbor AGG-T remote-as 65003
 neighbor AGG-T update-source lo

 neighbor 10.255.0.51 peer-group AGG-T
 neighbor 10.255.0.52 peer-group AGG-T
 neighbor 10.255.0.53 peer-group AGG-T

 !
 ! iBGP to CORE-A and CORE-C (if used)
 !
 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 neighbor CORE-C peer-group
 neighbor CORE-C remote-as 65002
 neighbor CORE-C update-source lo
 neighbor 10.255.0.21 peer-group CORE-C

 address-family l2vpn evpn
  neighbor AGG-T activate
  neighbor AGG-T route-reflector-client

  neighbor CORE-A activate
  neighbor CORE-C activate

  advertise-all-vni
 exit-address-family
!

router ospf
 router-id 10.255.0.41
 network 10.255.0.0/16 area 0
!