frr version 9
frr defaults traditional
hostname tor-a17
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.4.17/32

interface eth1
 ip address 10.255.30.9/31

router bgp 65001
 bgp router-id 10.255.4.17
 no bgp default ipv4-unicast

 neighbor AGG-A3 peer-group
 neighbor AGG-A3 remote-as 65001
 neighbor AGG-A3 update-source lo
 neighbor 10.255.0.13 peer-group AGG-A3

 address-family l2vpn evpn
  neighbor AGG-A3 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.4.17:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.4.17
 network 10.255.0.0/16 area 0