frr version 9
frr defaults traditional
hostname tor-a11
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.4.11/32

interface eth1
 ip address 10.255.20.9/31

router bgp 65001
 bgp router-id 10.255.4.11
 no bgp default ipv4-unicast

 neighbor AGG-A2 peer-group
 neighbor AGG-A2 remote-as 65001
 neighbor AGG-A2 update-source lo
 neighbor 10.255.0.12 peer-group AGG-A2

 address-family l2vpn evpn
  neighbor AGG-A2 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.4.11:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.4.11
 network 10.255.0.0/16 area 0