frr version 9
frr defaults traditional
hostname tor-a11
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.1.11/32

router bgp 65001
 bgp router-id 10.255.1.11
 no bgp default ipv4-unicast

 neighbor AGG-A2 peer-group
 neighbor AGG-A2 remote-as 65001
 neighbor AGG-A2 update-source lo
 neighbor 10.255.0.12 peer-group AGG-A2

 address-family l2vpn evpn
  neighbor AGG-A2 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.1.7:10102
  route-target import 65102:10102
  route-target export 65102:10102