frr version 9
frr defaults traditional
hostname tor-a18
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.1.18/32

router bgp 65001
 bgp router-id 10.255.1.18
 no bgp default ipv4-unicast

 neighbor AGG-A3 peer-group
 neighbor AGG-A3 remote-as 65001
 neighbor AGG-A3 update-source lo
 neighbor 10.255.0.13 peer-group AGG-A3

 address-family l2vpn evpn
  neighbor AGG-A3 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10103 l2
  rd 10.255.1.13:10103
  route-target import 65103:10103
  route-target export 65103:10103