frr version 9
frr defaults traditional
hostname tor-a2
log syslog informational
service integrated-vtysh-config

!
! Loopback
!
interface lo
 ip address 10.255.4.2/32
!

!
! Underlay link to agg-a1
! agg-a1:eth2 = 10.255.10.0/31
! tor-a1:eth1 = 10.255.10.1/31
!
interface eth1
 ip address 10.255.10.3/31
!

router bgp 65001
 bgp router-id 10.255.4.1
 no bgp default ipv4-unicast

 !
 ! iBGP to AGG-A1 (RR)
 !
 neighbor AGG-A1 peer-group
 neighbor AGG-A1 remote-as 65001
 neighbor AGG-A1 update-source lo
 neighbor 10.255.0.11 peer-group AGG-A1

 address-family l2vpn evpn
  neighbor AGG-A1 activate
  advertise-all-vni
 exit-address-family
!

evpn
 vni 10101 l2
  rd 10.255.4.2:10101
  route-target import 65101:10101
  route-target export 65101:10101
!

router ospf
 router-id 10.255.4.2
 network 10.255.0.0/16 area 0
!