frr version 9
frr defaults traditional
hostname tor-a6
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.1.6/32

router bgp 65001
 bgp router-id 10.255.1.6
 no bgp default ipv4-unicast

 neighbor AGG-A1 peer-group
 neighbor AGG-A1 remote-as 65001
 neighbor AGG-A1 update-source lo
 neighbor 10.255.0.11 peer-group AGG-A1

 address-family l2vpn evpn
  neighbor AGG-A1 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.1.1:10101
  route-target import 65101:10101
  route-target export 65101:10101