frr defaults traditional
hostname tor1
service integrated-vtysh-config
!
router bgp 65201
 bgp router-id 10.255.1.1
 no bgp default ipv4-unicast

 neighbor 10.255.0.2 remote-as 65100
 neighbor 10.255.0.2 description AGG

 address-family l2vpn evpn
  neighbor 10.255.0.2 activate

  ! Advertise VNI 10
  advertise-all-vni
 exit-address-family
!
line vty
