frr defaults traditional
hostname agg1
service integrated-vtysh-config

interface lo
 ip address 10.255.0.11/32

interface eth1
 ip address 10.0.0.11/31

interface eth2
 ip address 10.0.1.10/31

interface eth3
 ip address 10.0.1.12/31

router bgp 65101
 no bgp ebgp-requires-policy
 bgp router-id 10.255.0.11

 neighbor 10.0.0.10 remote-as 65000
 neighbor 10.0.1.11 remote-as 65201
 neighbor 10.0.1.13 remote-as 65202

 !
 ! -------------------------
 ! IPv4 Unicast (unchanged)
 ! -------------------------
 address-family ipv4 unicast
  network 10.255.0.11/32
  redistribute connected
 exit-address-family

 !
 ! -------------------------
 ! EVPN Address-Family
 ! -------------------------
 address-family l2vpn evpn
  neighbor 10.0.0.10 activate
  neighbor 10.0.1.11 activate
  neighbor 10.0.1.13 activate
 exit-address-family