frr defaults traditional
hostname tor2
service integrated-vtysh-config

vrf WAREHOUSE
 vni 50010

interface lo
 ip address 10.255.1.2/32

interface eth1
 ip address 10.0.1.13/31

interface eth2
 no ip address

interface bridge
 bridge-vlan-aware yes

vlan 10
 vni 10010

interface vlan10
 vrf WAREHOUSE
 ip address 192.168.10.1/24

interface vxlan10010
 vxlan id 10010
 vxlan local-tunnelip 10.255.1.2
 bridge-group 10

router bgp 65202
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.2

 neighbor 10.0.1.12 remote-as 65101

 address-family ipv4 unicast
  network 10.255.1.2/32
 exit-address-family

 address-family l2vpn evpn
  neighbor 10.0.1.12 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family

 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family