frr defaults traditional
hostname agg1
service integrated-vtysh-config

!
! =========================
! VRF (Tenant)
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback (Router-ID)
! =========================
interface lo
 ip address 10.255.1.1/32
exit

!
! =========================
! Core Facing Interfaces
! =========================
interface eth1
 description TO-CORE1
 ip address 10.0.0.1/31
exit

interface eth2
 description TO-CORE2
 ip address 10.0.0.9/31
exit

!
! =========================
! ToR Facing Interfaces
! =========================
interface eth3
 description TO-TOR1
 ip address 10.0.16.0/31
exit

interface eth4
 description TO-TOR2
 ip address 10.0.16.4/31
exit

interface eth5
 description TO-TOR3
 ip address 10.0.16.8/31
exit

interface eth6
 description TO-TOR4
 ip address 10.0.16.12/31
exit

!
! =========================
! BGP
! =========================
router bgp 65101
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.1

 !
 ! ---- Core Neighbors ----
 !
 neighbor 10.0.0.0 remote-as 65001
 neighbor 10.0.0.8 remote-as 65002

 !
 ! ---- ToR Neighbors ----
 !
 neighbor 10.0.16.1 remote-as 65201
 neighbor 10.0.16.5 remote-as 65202
 neighbor 10.0.16.9 remote-as 65203
 neighbor 10.0.16.13 remote-as 65204

 !
 ! =========================
 ! IPv4 Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.1/32
 exit-address-family

 !
 ! =========================
 ! EVPN Control Plane
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.0 activate
  neighbor 10.0.0.8 activate
  neighbor 10.0.16.1 activate
  neighbor 10.0.16.5 activate
  neighbor 10.0.16.9 activate
  neighbor 10.0.16.13 activate
  advertise-all-vni
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family