frr defaults traditional
hostname agg2
service integrated-vtysh-config

!
! =========================
! VRF (Tenant)
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.1.2/32
exit

!
! =========================
! Core Facing Interfaces
! =========================
interface eth1
 description TO-CORE1
 ip address 10.0.0.3/31
exit

interface eth2
 description TO-CORE2
 ip address 10.0.0.11/31
exit

!
! =========================
! ToR Facing Interfaces
! =========================
interface eth3
 description TO-TOR1
 ip address 10.0.16.3/31
exit

interface eth4
 description TO-TOR2
 ip address 10.0.16.7/31
exit

interface eth5
 description TO-TOR3
 ip address 10.0.16.11/31
exit

interface eth6
 description TO-TOR4
 ip address 10.0.16.15/31
exit

!
! =========================
! BGP
! =========================
router bgp 65102
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.2

 !
 ! ---- Core Neighbors ----
 !
 neighbor 10.0.0.2 remote-as 65001
 neighbor 10.0.0.10 remote-as 65002

 !
 ! ---- ToR Neighbors ----
 !
 neighbor 10.0.16.2 remote-as 65201
 neighbor 10.0.16.6 remote-as 65202
 neighbor 10.0.16.10 remote-as 65203
 neighbor 10.0.16.14 remote-as 65204

 !
 ! =========================
 ! IPv4 Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.2/32
 exit-address-family

 !
 ! =========================
 ! EVPN
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.10 activate
  neighbor 10.0.16.2 activate
  neighbor 10.0.16.6 activate
  neighbor 10.0.16.10 activate
  neighbor 10.0.16.14 activate
  advertise-all-vni
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family