frr defaults traditional
hostname agg3
service integrated-vtysh-config

!
! =========================
! VRF
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.1.3/32
exit

!
! =========================
! Core Facing Interfaces
! =========================
interface eth1
 description TO-CORE3
 ip address 10.0.0.17/31
exit

interface eth2
 description TO-CORE4
 ip address 10.0.0.19/31
exit

!
! =========================
! ToR Facing Interfaces
! =========================
interface eth3
 description TO-TOR5
 ip address 10.0.16.17/31
exit

interface eth4
 description TO-TOR6
 ip address 10.0.16.21/31
exit

interface eth5
 description TO-TOR7
 ip address 10.0.16.25/31
exit

interface eth6
 description TO-TOR8
 ip address 10.0.16.29/31
exit

!
! =========================
! BGP
! =========================
router bgp 65103
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.3

 !
 ! ---- Core Neighbors ----
 !
 neighbor 10.0.0.16 remote-as 65003
 neighbor 10.0.0.18 remote-as 65004

 !
 ! ---- ToR Neighbors ----
 !
 neighbor 10.0.16.16 remote-as 65205
 neighbor 10.0.16.20 remote-as 65206
 neighbor 10.0.16.24 remote-as 65207
 neighbor 10.0.16.28 remote-as 65208

 !
 ! =========================
 ! Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.3/32
 exit-address-family

 !
 ! =========================
 ! EVPN
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.16 activate
  neighbor 10.0.0.18 activate
  neighbor 10.0.16.16 activate
  neighbor 10.0.16.20 activate
  neighbor 10.0.16.24 activate
  neighbor 10.0.16.28 activate
  advertise-all-vni
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family