frr defaults traditional
hostname agg4
service integrated-vtysh-config

!
! =========================
! VRF
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.1.4/32
exit

!
! =========================
! Core Facing Interfaces
! =========================
interface eth1
 description TO-CORE3
 ip address 10.0.0.21/31
exit

interface eth2
 description TO-CORE4
 ip address 10.0.0.23/31
exit

!
! =========================
! ToR Facing Interfaces
! =========================
interface eth3
 description TO-TOR5
 ip address 10.0.16.19/31
exit

interface eth4
 description TO-TOR6
 ip address 10.0.16.23/31
exit

interface eth5
 description TO-TOR7
 ip address 10.0.16.27/31
exit

interface eth6
 description TO-TOR8
 ip address 10.0.16.31/31
exit

!
! =========================
! BGP
! =========================
router bgp 65104
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.4

 !
 ! ---- Core Neighbors ----
 !
 neighbor 10.0.0.20 remote-as 65003
 neighbor 10.0.0.22 remote-as 65004

 !
 ! ---- ToR Neighbors ----
 !
 neighbor 10.0.16.18 remote-as 65205
 neighbor 10.0.16.22 remote-as 65206
 neighbor 10.0.16.26 remote-as 65207
 neighbor 10.0.16.30 remote-as 65208

 !
 ! =========================
 ! Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.4/32
 exit-address-family

 !
 ! =========================
 ! EVPN
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.20 activate
  neighbor 10.0.0.22 activate
  neighbor 10.0.16.18 activate
  neighbor 10.0.16.22 activate
  neighbor 10.0.16.26 activate
  neighbor 10.0.16.30 activate
  advertise-all-vni
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family