frr defaults traditional
hostname agg5
service integrated-vtysh-config

!
! =========================
! VRF
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.1.5/32
exit

!
! =========================
! Core Facing Interfaces
! =========================
interface eth1
 description TO-CORE1
 ip address 10.0.0.25/31
exit

interface eth2
 description TO-CORE2
 ip address 10.0.0.27/31
exit

!
! =========================
! ToR Facing Interfaces
! =========================
interface eth3
 description TO-TOR9
 ip address 10.0.16.33/31
exit

interface eth4
 description TO-TOR10
 ip address 10.0.16.37/31
exit

interface eth5
 description TO-TOR11
 ip address 10.0.16.41/31
exit

interface eth6
 description TO-TOR12
 ip address 10.0.16.45/31
exit

!
! =========================
! BGP
! =========================
router bgp 65105
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.5

 !
 ! ---- Core Neighbors ----
 !
 neighbor 10.0.0.24 remote-as 65001
 neighbor 10.0.0.26 remote-as 65002

 !
 ! ---- ToR Neighbors ----
 !
 neighbor 10.0.16.32 remote-as 65209
 neighbor 10.0.16.36 remote-as 65210
 neighbor 10.0.16.40 remote-as 65211
 neighbor 10.0.16.44 remote-as 65212

 !
 ! =========================
 ! Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.5/32
 exit-address-family

 !
 ! =========================
 ! EVPN
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.24 activate
  neighbor 10.0.0.26 activate
  neighbor 10.0.16.32 activate
  neighbor 10.0.16.36 activate
  neighbor 10.0.16.40 activate
  neighbor 10.0.16.44 activate
  advertise-all-vni
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family