frr defaults traditional
hostname core1
service integrated-vtysh-config

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.0.1/32
exit

!
! =========================
! Aggregation Facing Interfaces
! =========================
interface eth1
 description TO-AGG1
 ip address 10.0.0.0/31
exit

interface eth2
 description TO-AGG2
 ip address 10.0.0.2/31
exit

interface eth3
 description TO-AGG5
 ip address 10.0.0.24/31
exit

interface eth4
 description TO-AGG7
 ip address 10.0.0.32/31
exit

!
! =========================
! BGP
! =========================
router bgp 65001
 no bgp ebgp-requires-policy
 bgp router-id 10.255.0.1

 !
 ! ---- Aggregation Neighbors ----
 !
 neighbor 10.0.0.1 remote-as 65101
 neighbor 10.0.0.3 remote-as 65102
 neighbor 10.0.0.25 remote-as 65105
 neighbor 10.0.0.33 remote-as 65107

 !
 ! =========================
 ! Underlay
 ! =========================
 address-family ipv4 unicast
  network 10.255.0.1/32
 exit-address-family

 !
 ! =========================
 ! EVPN Control Plane
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.3 activate
  neighbor 10.0.0.25 activate
  neighbor 10.0.0.33 activate
 exit-address-family