frr defaults traditional
hostname tor22
service integrated-vtysh-config

!
! =========================
! VRF
! =========================
vrf WAREHOUSE
 vni 50010
exit-vrf

!
! =========================
! Loopback
! =========================
interface lo
 ip address 10.255.1.22/32
exit

!
! =========================
! Uplink Interfaces to AGGs
! =========================
interface eth1
 description TO-AGG7
 ip address 10.0.16.84/31
exit

interface eth2
 description TO-AGG8
 ip address 10.0.16.88/31
exit

!
! =========================
! Downlink / Access Ports
! =========================
interface eth3
 no ip address
exit

!
! Bridge for VLAN 10
interface bridge
 bridge-vlan-aware yes
exit

vlan 10
 vni 10010
exit

! IRB interface for VLAN 10
interface vlan10
 vrf WAREHOUSE
 ip address 192.168.10.22/24
exit

! VXLAN interface
interface vxlan10010
 vxlan id 10010
 vxlan local-tunnelip 10.255.1.22
 bridge-group 10
exit

!
! =========================
! BGP
! =========================
router bgp 65222
 no bgp ebgp-requires-policy
 bgp router-id 10.255.1.22

 !
 ! ---- eBGP uplinks to AGGs ----
 !
 neighbor 10.0.16.83 remote-as 65107
 neighbor 10.0.16.87 remote-as 65108

 !
 ! =========================
 ! Underlay IPv4
 ! =========================
 address-family ipv4 unicast
  network 10.255.1.22/32
 exit-address-family

 !
 ! =========================
 ! EVPN
 ! =========================
 address-family l2vpn evpn
  neighbor 10.0.16.83 activate
  neighbor 10.0.16.87 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family

 !
 ! =========================
 ! Tenant VRF
 ! =========================
 address-family ipv4 unicast vrf WAREHOUSE
  redistribute connected
 exit-address-family