frr version 9
frr defaults traditional
hostname agg-c1
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.31/32

! core-c:eth1 <-> agg-c1:eth1
interface eth1
 ip address 10.255.1.1/31

! agg-c1:eth2 <-> tor-c1:eth1
interface eth2
 ip address 10.255.10.0/31

! agg-c1:eth3 <-> tor-c2:eth1
interface eth3
 ip address 10.255.10.2/31

! agg-c1:eth4 <-> tor-c3:eth1
interface eth4
 ip address 10.255.10.4/31

! agg-c1:eth5 <-> tor-c4:eth1
interface eth5
 ip address 10.255.10.6/31

! agg-c1:eth6 <-> tor-c5:eth1
interface eth6
 ip address 10.255.10.8/31

! agg-c1:eth7 <-> tor-c6:eth1
interface eth7
 ip address 10.255.10.10/31

router bgp 65002
 bgp router-id 10.255.0.31
 no bgp default ipv4-unicast

 neighbor CORE-C peer-group
 neighbor CORE-C remote-as 65002
 neighbor CORE-C update-source lo
 neighbor 10.255.0.21 peer-group CORE-C

 neighbor TOR-C1 peer-group
 neighbor TOR-C1 remote-as 65002
 neighbor TOR-C1 update-source lo

 neighbor 10.255.5.1 peer-group TOR-C1
 neighbor 10.255.5.2 peer-group TOR-C1
 neighbor 10.255.5.3 peer-group TOR-C1
 neighbor 10.255.5.4 peer-group TOR-C1
 neighbor 10.255.5.5 peer-group TOR-C1
 neighbor 10.255.5.6 peer-group TOR-C1

 address-family l2vpn evpn
  neighbor CORE-C activate
  neighbor TOR-C1 activate
  neighbor TOR-C1 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.0.31:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.0.31
 network 10.255.0.31/32 area 0
 network 10.255.1.1/31 area 0