frr version 9
frr defaults traditional
hostname agg-c2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.32/32

router bgp 65002
 bgp router-id 10.255.0.32
 no bgp default ipv4-unicast

 neighbor CORE-C peer-group
 neighbor CORE-C remote-as 65002
 neighbor CORE-C update-source lo
 neighbor 10.255.0.21 peer-group CORE-C

 neighbor TOR-C2 peer-group
 neighbor TOR-C2 remote-as 65002
 neighbor TOR-C2 update-source lo

 neighbor 10.255.2.7  peer-group TOR-C2
 neighbor 10.255.2.8  peer-group TOR-C2
 neighbor 10.255.2.9  peer-group TOR-C2
 neighbor 10.255.2.10 peer-group TOR-C2
 neighbor 10.255.2.11 peer-group TOR-C2
 neighbor 10.255.2.12 peer-group TOR-C2

 address-family l2vpn evpn
  neighbor CORE-C activate
  neighbor TOR-C2 activate
  neighbor TOR-C2 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.0.32:10102
  route-target import 65102:10102
  route-target export 65102:10102