frr version 9
frr defaults traditional
hostname agg-c3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.33/32

! core-c:eth3 <-> agg-c3:eth1
interface eth1
 ip address 10.255.1.5/31

! agg-c3:eth2 <-> tor-c13:eth1
interface eth2
 ip address 10.255.30.0/31

! agg-c3:eth3 <-> tor-c14:eth1
interface eth3
 ip address 10.255.30.2/31

! agg-c3:eth4 <-> tor-c15:eth1
interface eth4
 ip address 10.255.30.4/31

! agg-c3:eth5 <-> tor-c16:eth1
interface eth5
 ip address 10.255.30.6/31

! agg-c3:eth6 <-> tor-c17:eth1
interface eth6
 ip address 10.255.30.8/31

! agg-c3:eth7 <-> tor-c18:eth1
interface eth7
 ip address 10.255.30.10/31

router bgp 65002
 bgp router-id 10.255.0.33
 no bgp default ipv4-unicast

 neighbor CORE-C peer-group
 neighbor CORE-C remote-as 65002
 neighbor CORE-C update-source lo
 neighbor 10.255.0.21 peer-group CORE-C

 neighbor TOR-C3 peer-group
 neighbor TOR-C3 remote-as 65002
 neighbor TOR-C3 update-source lo

 neighbor 10.255.5.13 peer-group TOR-C3
 neighbor 10.255.5.14 peer-group TOR-C3
 neighbor 10.255.5.15 peer-group TOR-C3
 neighbor 10.255.5.16 peer-group TOR-C3
 neighbor 10.255.5.17 peer-group TOR-C3
 neighbor 10.255.5.18 peer-group TOR-C3

 address-family l2vpn evpn
  neighbor CORE-C activate
  neighbor TOR-C3 activate
  neighbor TOR-C3 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.0.33:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.0.33
 network 10.255.0.33/32 area 0
 network 10.255.1.5/31 area 0