frr version 9
frr defaults traditional
hostname agg-c3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.33/32

router bgp 65002
 bgp router-id 10.255.0.33
 no bgp default ipv4-unicast

 neighbor CORE-C peer-group
 neighbor CORE-C remote-as 65002
 neighbor CORE-C update-source lo
 neighbor 10.255.0.21 peer-group CORE-C

 neighbor TOR-C3 peer-group
 neighbor TOR-C3 remote-as 65002
 neighbor TOR-C3 update-source lo

 neighbor 10.255.2.13 peer-group TOR-C3
 neighbor 10.255.2.14 peer-group TOR-C3
 neighbor 10.255.2.15 peer-group TOR-C3
 neighbor 10.255.2.16 peer-group TOR-C3
 neighbor 10.255.2.17 peer-group TOR-C3
 neighbor 10.255.2.18 peer-group TOR-C3

 address-family l2vpn evpn
  neighbor CORE-C activate
  neighbor TOR-C3 activate
  neighbor TOR-C3 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10103 l2
  rd 10.255.0.33:10103
  route-target import 65103:10103
  route-target export 65103:10103