frr version 9
frr defaults traditional
hostname agg-a1
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.11/32

! core-a:eth1 <-> agg-a1:eth1
interface eth1
 ip address 10.255.1.1/31

! agg-a1:eth2 <-> tor-a1:eth1
interface eth2
 ip address 10.255.10.0/31

! agg-a1:eth3 <-> tor-a2:eth1
interface eth3
 ip address 10.255.10.2/31

! agg-a1:eth4 <-> tor-a3:eth1
interface eth4
 ip address 10.255.10.4/31

! agg-a1:eth5 <-> tor-a4:eth1
interface eth5
 ip address 10.255.10.6/31

! agg-a1:eth6 <-> tor-a5:eth1
interface eth6
 ip address 10.255.10.8/31

! agg-a1:eth7 <-> tor-a6:eth1
interface eth7
 ip address 10.255.10.10/31

router bgp 65001
 bgp router-id 10.255.0.11
 no bgp default ipv4-unicast

 ! iBGP to core-a
 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 ! iBGP to ToRs (RR)
 neighbor TOR-A1 peer-group
 neighbor TOR-A1 remote-as 65001
 neighbor TOR-A1 update-source lo

 neighbor 10.255.4.1 peer-group TOR-A1
 neighbor 10.255.4.2 peer-group TOR-A1
 neighbor 10.255.4.3 peer-group TOR-A1
 neighbor 10.255.4.4 peer-group TOR-A1
 neighbor 10.255.4.5 peer-group TOR-A1
 neighbor 10.255.4.6 peer-group TOR-A1

 address-family l2vpn evpn
  neighbor CORE-A activate
  neighbor TOR-A1 activate
  neighbor TOR-A1 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.0.11:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.0.11
 network 10.255.0.11/32 area 0
 network 10.255.1.1/31 area 0