frr version 9
frr defaults traditional
hostname agg-a2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.12/32

! core-a:eth2 <-> agg-a2:eth1
interface eth1
 ip address 10.255.1.3/31

! agg-a2:eth2 <-> tor-a7:eth1
interface eth2
 ip address 10.255.20.0/31

! agg-a2:eth3 <-> tor-a8:eth1
interface eth3
 ip address 10.255.20.2/31

! agg-a2:eth4 <-> tor-a9:eth1
interface eth4
 ip address 10.255.20.4/31

! agg-a2:eth5 <-> tor-a10:eth1
interface eth5
 ip address 10.255.20.6/31

! agg-a2:eth6 <-> tor-a11:eth1
interface eth6
 ip address 10.255.20.8/31

! agg-a2:eth7 <-> tor-a12:eth1
interface eth7
 ip address 10.255.20.10/31

router bgp 65001
 bgp router-id 10.255.0.12
 no bgp default ipv4-unicast

 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 neighbor TOR-A2 peer-group
 neighbor TOR-A2 remote-as 65001
 neighbor TOR-A2 update-source lo

 neighbor 10.255.4.7 peer-group TOR-A2
 neighbor 10.255.4.8 peer-group TOR-A2
 neighbor 10.255.4.9 peer-group TOR-A2
 neighbor 10.255.4.10 peer-group TOR-A2
 neighbor 10.255.4.11 peer-group TOR-A2
 neighbor 10.255.4.12 peer-group TOR-A2

 address-family l2vpn evpn
  neighbor CORE-A activate
  neighbor TOR-A2 activate
  neighbor TOR-A2 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.0.12:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.0.12
 network 10.255.0.12/32 area 0
 network 10.255.1.3/31 area 0