frr version 9
frr defaults traditional
hostname agg-a2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.12/32

router bgp 65001
 bgp router-id 10.255.0.12
 no bgp default ipv4-unicast

 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 neighbor TOR-A2 peer-group
 neighbor TOR-A2 remote-as 65001
 neighbor TOR-A2 update-source lo

 neighbor 10.255.1.7  peer-group TOR-A2
 neighbor 10.255.1.8  peer-group TOR-A2
 neighbor 10.255.1.9  peer-group TOR-A2
 neighbor 10.255.1.10 peer-group TOR-A2
 neighbor 10.255.1.11 peer-group TOR-A2
 neighbor 10.255.1.12 peer-group TOR-A2

 address-family l2vpn evpn
  neighbor CORE-A activate

  neighbor TOR-A2 activate
  neighbor TOR-A2 route-reflector-client

  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.0.12:10102
  route-target import 65102:10102
  route-target export 65102:10102