frr version 9
frr defaults traditional
hostname agg-a3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.13/32

router bgp 65001
 bgp router-id 10.255.0.13
 no bgp default ipv4-unicast

 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 neighbor TOR-A3 peer-group
 neighbor TOR-A3 remote-as 65001
 neighbor TOR-A3 update-source lo

 neighbor 10.255.1.13 peer-group TOR-A3
 neighbor 10.255.1.14 peer-group TOR-A3
 neighbor 10.255.1.15 peer-group TOR-A3
 neighbor 10.255.1.16 peer-group TOR-A3
 neighbor 10.255.1.17 peer-group TOR-A3
 neighbor 10.255.1.18 peer-group TOR-A3

 address-family l2vpn evpn
  neighbor CORE-A activate

  neighbor TOR-A3 activate
  neighbor TOR-A3 route-reflector-client

  advertise-all-vni
 exit-address-family

evpn
 vni 10103 l2
  rd 10.255.0.13:10103
  route-target import 65103:10103
  route-target export 65103:10103