frr version 9
frr defaults traditional
hostname agg-a3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.13/32

! core-a:eth3 <-> agg-a3:eth1
interface eth1
 ip address 10.255.1.5/31

! agg-a3:eth2 <-> tor-a13:eth1
interface eth2
 ip address 10.255.30.0/31

! agg-a3:eth3 <-> tor-a14:eth1
interface eth3
 ip address 10.255.30.2/31

! agg-a3:eth4 <-> tor-a15:eth1
interface eth4
 ip address 10.255.30.4/31

! agg-a3:eth5 <-> tor-a16:eth1
interface eth5
 ip address 10.255.30.6/31

! agg-a3:eth6 <-> tor-a17:eth1
interface eth6
 ip address 10.255.30.8/31

! agg-a3:eth7 <-> tor-a18:eth1
interface eth7
 ip address 10.255.30.10/31

router bgp 65001
 bgp router-id 10.255.0.13
 no bgp default ipv4-unicast

 neighbor CORE-A peer-group
 neighbor CORE-A remote-as 65001
 neighbor CORE-A update-source lo
 neighbor 10.255.0.1 peer-group CORE-A

 neighbor TOR-A3 peer-group
 neighbor TOR-A3 remote-as 65001
 neighbor TOR-A3 update-source lo

 neighbor 10.255.4.13 peer-group TOR-A3
 neighbor 10.255.4.14 peer-group TOR-A3
 neighbor 10.255.4.15 peer-group TOR-A3
 neighbor 10.255.4.16 peer-group TOR-A3
 neighbor 10.255.4.17 peer-group TOR-A3
 neighbor 10.255.4.18 peer-group TOR-A3

 address-family l2vpn evpn
  neighbor CORE-A activate
  neighbor TOR-A3 activate
  neighbor TOR-A3 route-reflector-client
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.0.13:10101
  route-target import 65101:10101
  route-target export 65101:10101

router ospf
 router-id 10.255.0.13
 network 10.255.0.0/16 area 0