frr defaults traditional
hostname core-a
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description to-agg-a
!
interface eth2
 description to-core-t
 ip address 10.0.3.0/31
!
interface eth3
 description to-core-c
 ip address 10.0.2.1/31
!
router bgp 65000
 bgp router-id 10.255.0.3
 neighbor 10.0.3.1 remote-as 65000
 neighbor 10.0.2.0 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 10.0.3.1 activate
  neighbor 10.0.2.0 activate
 exit-address-family
!
line vty