frr version 9
frr defaults traditional
hostname core-a
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.1/32

! core-a:eth1 <-> agg-a1:eth1
interface eth1
 ip address 10.255.1.0/31

! core-a:eth2 <-> agg-a2:eth1
interface eth2
 ip address 10.255.1.2/31

! core-a:eth3 <-> agg-a3:eth1
interface eth3
 ip address 10.255.1.4/31

router bgp 65001
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast

 ! iBGP to AGGs
 neighbor AGG-A peer-group
 neighbor AGG-A remote-as 65001
 neighbor AGG-A update-source lo

 neighbor 10.255.0.11 peer-group AGG-A
 neighbor 10.255.0.12 peer-group AGG-A
 neighbor 10.255.0.13 peer-group AGG-A

 ! EVPN peering to core-t (AS 65003)
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 address-family l2vpn evpn
  neighbor AGG-A activate
  neighbor AGG-A route-reflector-client

  neighbor CORE-T activate

  advertise-all-vni
 exit-address-family

router ospf
 router-id 10.255.0.1
 network 10.255.0.0/16 area 0
 network 10.0.2.0/31 area 0
 network 10.0.3.0/31 area 0