frr version 9
frr defaults traditional
hostname core-a
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.1/32
 ip ospf area 0
 ip ospf passive


! core-a:eth1 <-> agg-a1:eth1
interface eth1
 ip address 10.255.1.0/31

! core-a:eth2 <-> agg-a2:eth1
interface eth2
 ip address 10.255.1.2/31

! core-a:eth3 <-> agg-a3:eth1
interface eth3
 ip address 10.255.1.4/31

interface vxlan-ac
 ip ospf area 0

interface vxlan-at
 ip ospf area 0


router bgp 65001
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast

 ! iBGP to AGG-A over underlay /31s
 neighbor 10.255.1.1 remote-as 65001
 neighbor 10.255.1.1 update-source eth1

 neighbor 10.255.1.3 remote-as 65001
 neighbor 10.255.1.3 update-source eth2

 neighbor 10.255.1.5 remote-as 65001
 neighbor 10.255.1.5 update-source eth3

 ! EVPN peering to core-t (AS 65003) via loopback
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 address-family l2vpn evpn
  neighbor 10.255.1.1 activate
  neighbor 10.255.1.3 activate
  neighbor 10.255.1.5 activate

  neighbor CORE-T activate

  advertise-all-vni
 exit-address-family

router ospf
 ospf router-id 10.255.0.1
 network 10.0.0.0/8 area 0
 network 10.255.0.0/24 area 0
 passive-interface lo
