frr defaults traditional
hostname core-c
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.1/31
 ip ospf area 0
!
interface eth2
 ip address 10.0.3.0/31
 ip ospf area 0
!
interface lo
 ip address 10.255.0.21/32
!
interface vxlan10000
 vxlan id 10000
 vxlan local-tunnelip 10.255.0.21
 vxlan udp-port 4789
!
interface vlan10
 ip address 192.168.10.2/24
!
router ospf
 router-id 10.255.0.21
 network 10.0.1.0/31 area 0
 network 10.0.3.0/31 area 0
 network 10.255.0.21/32 area 0
!
router bgp 65000
 bgp router-id 10.255.0.21
 no bgp default ipv4-unicast
 neighbor A peer-group
 neighbor A remote-as 65000
 neighbor A update-source lo
 neighbor T peer-group
 neighbor T remote-as 65000
 neighbor T update-source lo
 neighbor 10.255.0.1 peer-group A
 neighbor 10.255.0.41 peer-group T
 !
 address-family ipv4 unicast
  network 192.168.10.0/24
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor A activate
  neighbor T activate
  advertise-all-vni
 exit-address-family
!
router evpn
 vni 10000 l2
  rd 10.255.0.21:10000
  route-target import 65000:10000
  route-target export 65000:10000
!
line vty
!