frr defaults traditional
hostname core
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast

 neighbor 10.255.0.2 remote-as 65100
 neighbor 10.255.0.2 description AGG

 address-family l2vpn evpn
  neighbor 10.255.0.2 activate
 exit-address-family
!
line vty
