frr defaults traditional
hostname core-t
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.2.1/31
 ip ospf area 0
!
interface eth2
 ip address 10.0.3.1/31
 ip ospf area 0
!
interface lo
 ip address 10.255.0.41/32
!
interface vxlan10000
 vxlan id 10000
 vxlan local-tunnelip 10.255.0.41
 vxlan udp-port 4789
!
interface vlan10
 ip address 192.168.10.3/24
!
router ospf
 router-id 10.255.0.41
 network 10.0.2.0/31 area 0
 network 10.0.3.0/31 area 0
 network 10.255.0.41/32 area 0
!
router bgp 65000
 bgp router-id 10.255.0.41
 no bgp default ipv4-unicast
 neighbor A peer-group
 neighbor A remote-as 65000
 neighbor A update-source lo
 neighbor C peer-group
 neighbor C remote-as 65000
 neighbor C update-source lo
 neighbor 10.255.0.1 peer-group A
 neighbor 10.255.0.21 peer-group C
 !
 address-family ipv4 unicast
  network 192.168.10.0/24
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor A activate
  neighbor C activate
  advertise-all-vni
 exit-address-family
!
router evpn
 vni 10000 l2
  rd 10.255.0.41:10000
  route-target import 65000:10000
  route-target export 65000:10000
!
line vty
!