frr version 9
frr defaults traditional
hostname tor-t17
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.3.17/32

interface eth1
 ip address 10.255.30.9/31

router bgp 65003
 bgp router-id 10.255.3.17
 no bgp default ipv4-unicast

 neighbor AGG-T3 peer-group
 neighbor AGG-T3 remote-as 65003
 neighbor AGG-T3 update-source lo
 neighbor 10.255.0.53 peer-group AGG-T3

 address-family l2vpn evpn
  neighbor AGG-T3 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10103 l2
  rd 10.255.3.17:10103
  route-target import 65103:10103
  route-target export 65103:10103

router ospf
 router-id 10.255.3.17
 network 10.255.0.0/16 area 0
