frr version 9
frr defaults traditional
hostname tor-t5
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.3.5/32

router bgp 65003
 bgp router-id 10.255.3.5
 no bgp default ipv4-unicast

 neighbor AGG-T1 peer-group
 neighbor AGG-T1 remote-as 65003
 neighbor AGG-T1 update-source lo
 neighbor 10.255.0.51 peer-group AGG-T1

 address-family l2vpn evpn
  neighbor AGG-T1 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10101 l2
  rd 10.255.3.5:10101
  route-target import 65101:10101
  route-target export 65101:10101