frr version 9
frr defaults traditional
hostname tor-t9
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.3.9/32

interface eth1
 ip address 10.255.20.5/31

router bgp 65003
 bgp router-id 10.255.3.9
 no bgp default ipv4-unicast

 neighbor AGG-T2 peer-group
 neighbor AGG-T2 remote-as 65003
 neighbor AGG-T2 update-source lo
 neighbor 10.255.0.52 peer-group AGG-T2

 address-family l2vpn evpn
  neighbor AGG-T2 activate
  advertise-all-vni
 exit-address-family

evpn
 vni 10102 l2
  rd 10.255.3.9:10102
  route-target import 65102:10102
  route-target export 65102:10102