frr version 7.5.1
frr defaults traditional
hostname leaf3
service integrated-vtysh-config
log syslog informational

interface eth1
 ip address 10.0.0.9/30
 ip ospf priority 0
 no shutdown
interface eth2
 ip address 10.0.0.11/30
 ip ospf priority 0
 no shutdown
interface eth3
 no ip address
 no shutdown
interface lo
 ip address 10.255.1.3/32
 no shutdown

router ospf
 ospf router-id 10.255.1.3 
 network 10.0.0.9/30 area 0
 network 10.0.0.11/30 area 0
 network 10.255.1.3/32 area 0

interface br10
 ip address 192.168.10.3/24
 bridge vni 10
 evpn arp-nd-suppress
 evpn
 no shutdown

interface vxlan10
 vxlan id 10
 vxlan local-tunnelip 10.255.1.3
 bridge-access 10
 evpn
 no shutdown

router bgp 65000
 bgp router-id 10.255.1.3

 neighbor SPINES peer-group
 neighbor SPINES remote-as 65000
 neighbor SPINES update-source lo

 neighbor 10.255.0.1 peer-group SPINES
 neighbor 10.255.0.2 peer-group SPINES

 address-family l2vpn evpn
  neighbor SPINES activate
  advertise-all-vni
  advertise-svi-ip
  vni 10
   rd 10.255.1.3:10
   route-target import 65000:10
   route-target export 65000:10
 exit-address-family


line vty