frr defaults traditional
hostname agg
service integrated-vtysh-config
!
router bgp 65100
 bgp router-id 10.255.0.2
 no bgp default ipv4-unicast

 ! Peer with core
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 description CORE

 ! Peer with ToR1
 neighbor 10.255.1.1 remote-as 65201
 neighbor 10.255.1.1 description ToR1

 ! Peer with ToR2
 neighbor 10.255.1.2 remote-as 65202
 neighbor 10.255.1.2 description ToR2

 address-family l2vpn evpn
  neighbor 10.255.0.1 activate
  neighbor 10.255.1.1 activate
  neighbor 10.255.1.2 activate
 exit-address-family
!
line vty
