frr version 9
frr defaults traditional
hostname core-c
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.255.0.21/32

! core-c:eth1 <-> agg-c1:eth1
interface eth1
 ip address 10.255.1.0/31

! core-c:eth2 <-> agg-c2:eth1
interface eth2
 ip address 10.255.1.2/31

! core-c:eth3 <-> agg-c3:eth1
interface eth3
 ip address 10.255.1.4/31

router bgp 65002
 bgp router-id 10.255.0.21
 no bgp default ipv4-unicast

 ! iBGP to AGGs
 neighbor AGG-C peer-group
 neighbor AGG-C remote-as 65002
 neighbor AGG-C update-source lo

 neighbor 10.255.0.31 peer-group AGG-C
 neighbor 10.255.0.32 peer-group AGG-C
 neighbor 10.255.0.33 peer-group AGG-C

 ! EVPN peering to core-t (AS 65003)
 neighbor CORE-T peer-group
 neighbor CORE-T remote-as 65003
 neighbor CORE-T update-source lo
 neighbor 10.255.0.41 peer-group CORE-T

 address-family l2vpn evpn
  neighbor AGG-C activate
  neighbor AGG-C route-reflector-client

  neighbor CORE-T activate

  advertise-all-vni
 exit-address-family

router ospf
 router-id 10.255.0.21
 network 10.255.0.0/16 area 0